---
# This role contains plays to install and configure the base splunk instance

- name: Update hostname in /etc/sysconfig/network
  shell: sed -i "/HOSTNAME=localhost.localdomain/ c\\HOSTNAME=`curl http://169.254.169.254/latest/meta-data/instance-id`.{{ splunk_host_domain }}" /etc/sysconfig/network

- name: Dynamically change hostname
  shell: "hostname `curl http://169.254.169.254/latest/meta-data/instance-id`.{{ splunk_host_domain }}"

- name: Install Splunk server binary
  yum: name="{{ splunk_binary_url }}" state=installed

- name: Copy scripts to run
  copy: src="{{ item }}" dest="/home/ec2-user/{{ item }}" mode=755
  with_items:
   - config_splunk_inputs.sh

- name: Execute config_splunk_inputs.sh script
  shell: /home/ec2-user/config_splunk_inputs.sh

- name: Clean up shell file
  file: name=/home/ec2-user/config_splunk_inputs.sh state=absent

- name: Start Splunk for the first time
  command: /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd {{ splunk_admin_passwd}}

- name: Enable Splunk to auto-start on boot
  command: /bin/su --shell=/bin/bash --session-command="/opt/splunk/bin/splunk enable boot-start -user splunk"

- name: Set appropriate file ACLs for /var/log
  command: /usr/bin/setfacl -m "u:splunk:r-x" /var/log
  command: /usr/bin/setfacl -m "u:splunk:r--" /var/log/*
  command: /usr/bin/setfacl -m d:user:splunk:r /var/log
